version: '3.1'
services:
  stats-server:
    build: ./stat-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ExploreWithMeStats
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    depends_on:
      - stats-db
  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ExploreWithMeStats
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
  ewm-service:
    build: ./main-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ExploreWithMe
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - stats.url=http://stats-server:9090
    depends_on:
      - ewm-db
  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ExploreWithMe
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password