version: '3.1'
services:
  stats-server:
    build: ./stat-service
    image: stats
    container_name: explore-with-me-stats
    depends_on:
      - ewm-service
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ExploreWithMeStats

  stats-db:
    image: postgres:14-alpine
    container_name: explore-with-me-stats-postgres
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ExploreWithMeStats
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./main-service
    image: ewm
    container_name: explore-with-me-ewm
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ExploreWithMe
      - ewm-stat.url=http://stats-server:9090
      - application.name=ewm-main-service

  ewm-db:
    image: postgres:14-alpine
    container_name: explore-with-me-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ExploreWithMe
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password