/*DROP TABLE IF EXISTS endpoint_hit;*/

CREATE TABLE IF NOT EXISTS endpoint_hit (
    endpoint_hit_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app VARCHAR(150) ,
    uri VARCHAR(150),
    ip VARCHAR(30),
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT endpoint_hit_id_pk PRIMARY KEY (endpoint_hit_id)
);